name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Poetry
        uses: poetry-actions/setup-poetry@v2
        with:
          python-version: 3.x

      - name: Install dependencies with Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
        env:
          POETRY_VERSION: 1.4.2  # Replace with your desired Poetry version

      - name: Lint code with Ruff
        run: run poetry run ruff .

      - name: Run tests
        run: run poetry run pytest

      # Add more steps for deployment as needed
